using System.Collections;
using System.IO;
using NUnit.Framework;
using UnityEngine;
using UnityEngine.TestTools;
using VRGloveDataCapture.Capture;

namespace VRGloveDataCapture.Tests
{
    public sealed class UnifiedCaptureSmokeTests
    {
        private const string ParticipantId = "AUTOMATED_CAPTURE_TEST";
        private string participantRoot;
        private string latestPointerPath;
        private string previousLatestPointer;
        private bool latestPointerExisted;

        [SetUp]
        public void SetUp()
        {
            participantRoot = Path.Combine(
                CaptureSessionManager.CaptureRootDirectory,
                "participants",
                ParticipantId);
            latestPointerPath = Path.Combine(CaptureSessionManager.CaptureRootDirectory, "LATEST_TRIAL.txt");
            latestPointerExisted = File.Exists(latestPointerPath);
            previousLatestPointer = latestPointerExisted ? File.ReadAllText(latestPointerPath) : null;
            if (Directory.Exists(participantRoot))
            {
                Directory.Delete(participantRoot, true);
            }
        }

        [TearDown]
        public void TearDown()
        {
            if (Directory.Exists(participantRoot))
            {
                Directory.Delete(participantRoot, true);
            }

            if (latestPointerExisted)
            {
                Directory.CreateDirectory(Path.GetDirectoryName(latestPointerPath));
                File.WriteAllText(latestPointerPath, previousLatestPointer);
            }
            else if (File.Exists(latestPointerPath))
            {
                File.Delete(latestPointerPath);
            }
        }

        [UnityTest]
        public IEnumerator TrialFinalizesAtomicMachineReadableStreamsAndManifest()
        {
            yield return null;

            CaptureSessionManager manager = CaptureSessionManager.Instance;
            if (manager == null)
            {
                GameObject managerObject = new GameObject("Unified Capture Test Manager");
                manager = managerObject.AddComponent<CaptureSessionManager>();
                yield return null;
            }

            if (manager.IsRecording)
            {
                manager.StopTrial();
            }

            GameObject trackedObject = GameObject.CreatePrimitive(PrimitiveType.Cube);
            trackedObject.name = "Automated Tracked Cube";
            trackedObject.AddComponent<Rigidbody>().isKinematic = true;
            trackedObject.AddComponent<CaptureTrackedObject>();

            CaptureProfile profile = new CaptureProfile
            {
                participantId = ParticipantId,
                sessionLabel = "smoke-test",
                taskId = "capture-pipeline",
                condition = "no-hardware",
                operatorId = "automation",
                notes = "Generated by UnifiedCaptureSmokeTests",
                sampleRateHz = 60,
                recordVideo = false,
                captureRawImuIfAvailable = true,
                requireHandTracking = false
            };

            manager.StartNewSession();
            manager.ApplyProfile(profile);
            Assert.IsTrue(manager.StartTrial(), manager.LastError);
            CaptureEventBus.Publish("test_event", "capture-pipeline", "Automated Tracked Cube", "value=42");

            yield return null;
            trackedObject.transform.position = new Vector3(0.1f, 0.2f, 0.3f);
            yield return null;
            yield return null;

            manager.StopTrial();
            string trialDirectory = manager.LastTrialDirectory;

            Assert.IsTrue(Directory.Exists(trialDirectory));
            Assert.IsTrue(File.Exists(Path.Combine(trialDirectory, "COMPLETE")));
            Assert.IsFalse(File.Exists(Path.Combine(trialDirectory, "INCOMPLETE")));
            Assert.IsTrue(File.Exists(Path.Combine(trialDirectory, "manifest.json")));
            Assert.IsTrue(File.Exists(Path.Combine(trialDirectory, "checksums.sha256")));
            Assert.IsTrue(File.Exists(Path.Combine(trialDirectory, "streams", "frame_timing.csv")));
            Assert.IsTrue(File.Exists(Path.Combine(trialDirectory, "streams", "hand_bones.csv")));
            Assert.IsTrue(File.Exists(Path.Combine(trialDirectory, "streams", "joint_angles.csv")));
            Assert.IsTrue(File.Exists(Path.Combine(trialDirectory, "streams", "objects.csv")));
            Assert.IsTrue(File.Exists(Path.Combine(trialDirectory, "streams", "devices.csv")));
            Assert.IsTrue(File.Exists(Path.Combine(trialDirectory, "streams", "hi5_sensor_status.csv")));
            Assert.IsTrue(File.Exists(Path.Combine(trialDirectory, "events", "events.csv")));

            string events = File.ReadAllText(Path.Combine(trialDirectory, "events", "events.csv"));
            StringAssert.Contains("test_event", events);
            StringAssert.Contains("trial_started", events);
            StringAssert.Contains("trial_stopping", events);

            string objects = File.ReadAllText(Path.Combine(trialDirectory, "streams", "objects.csv"));
            StringAssert.Contains("Automated-Tracked-Cube", objects);

            string manifest = File.ReadAllText(Path.Combine(trialDirectory, "manifest.json"));
            StringAssert.Contains("\"status\": \"complete\"", manifest);
            StringAssert.Contains("\"rawImuStatus\"", manifest);
            StringAssert.Contains(ParticipantId, manifest);

            string[] partialFiles = Directory.GetFiles(trialDirectory, "*.partial", SearchOption.AllDirectories);
            Assert.AreEqual(0, partialFiles.Length, "Finalized trials must not retain partial files.");

            Object.Destroy(trackedObject);
        }
    }
}
